language: c
sudo: required
env:
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.08
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.10

os:
  - linux
  - osx

cache:
  directories:
    - $HOME/.opam

before_install:
  - bash -ex .travis-ocaml.sh
  - opam install -y ppx_deriving ocamlfind ocamlbuild
  - opam install -y batteries 
  - opam install -y ANSIterminal cmdliner fmt alcotest logs
  - opam install -y -v z3=4.8.1
  - LD_LIBRARY_PATH="$(opam var lib)/z3:$LD_LIBRARY_PATH"
  - export LD_LIBRARY_PATH
  - DYLD_FALLBACK_LIBRARY_PATH="$(opam var lib)/z3:$DYLD_FALLBACK_LIBRARY_PATH"
  - export DYLD_FALLBACK_LIBRARY_PATH
script:
  - ls -lR $(opam var lib)/z3
  - ls -lR $(opam var lib)/stublibs
  - opam exec -- dune build src/kmt
  - opam exec -- dune exec src/kmt -vv --addition "x<2;inc(x,1)" "x<1;inc(x,1) + x<2;inc(x,1)"
  - opam exec -- dune exec src/test_equivalence.exe
  - opam exec -- dune exec src/test_word.exe


