language: c
sudo: required
env:
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.08
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.10

os:
  - linux
  - osx

cache:
  directories:
    - $HOME/.opam

before_install:
  - bash -ex .travis-ocaml.sh
  - opam install -y ppx_deriving ocamlfind ocamlbuild
  - opam install -y batteries 
  - opam install -y ANSIterminal cmdliner fmt alcotest logs
  - opam install -y -v z3=4.8.1
  - LD_LIBRARY_PATH="$(opam var lib)/z3:$LD_LIBRARY_PATH"
  - export LD_LIBRARY_PATH
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then DYLD_LIBRARY_PATH="$(opam var lib)/z3:$DYLD_LIBRARY_PATH"; export DYLD_LIBRARY_PATH; echo $DYLD_LIBRARY_PATH; fi
script:
  - ls -lR $(opam var lib)/z3
  - ls -lR $(opam var lib)/stublibs
  - opam config exec -- dune build src/main.exe
  - opam config exec -- dune exec src/test_equivalence.exe
  - opam config exec -- dune exec src/test_word.exe


