language: c
sudo: required
env:
  - OCAML_VERSION=4.07

cache:
  directories:
    - $HOME/.opam

before_install:
  - travis_wait bash -ex .travis-ocaml.sh
  - travis_wait opam install -y ppx_deriving
  - travis_wait opam install -y ocamlbuild
  - travis_wait opam install -y batteries 
  - travis_wait opam install -y ANSIterminal 
  - travis_wait opam install -y z3 
script:
  - make
  - make test
  - make eval

